/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    FormTitleCards: typeof import('./components/FormTitleCards.vue')['default']
    HeroHomeCard: typeof import('./components/HeroHomeCard.vue')['default']
    Preloader: typeof import('./components/Preloader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInForm: typeof import('./components/account/SignInForm.vue')['default']
    SignUpForm: typeof import('./components/account/SignUpForm.vue')['default']
  }
}
