/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/example/AppFooter.vue')['default']
    AuthDialog: typeof import('./components/AuthDialog.vue')['default']
    AuthDialogue: typeof import('./components/AuthDialog.vue')['default']
    HelloWorld: typeof import('./components/example/HelloWorld.vue')['default']
    LandingPageHeader: typeof import('./pages/index.vue')['default']
    P5Canvas: typeof import('./components/P5Canvas.vue')['default']
    Preloader: typeof import('./components/Preloader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sketch: typeof import('./components/Sketch.vue')['default']
  }
}
