/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/Alert.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    copy: typeof import('./components/user/UserMatchCard copy.vue')['default']
    EditProfile: typeof import('./components/user/EditProfile.vue')['default']
    FormTitleCards: typeof import('./components/FormTitleCards.vue')['default']
    HeroHomeCard: typeof import('./components/HeroHomeCard.vue')['default']
    HomeFooter: typeof import('./components/HomeFooter.vue')['default']
    HomeHeader: typeof import('./components/HomeHeader.vue')['default']
    MatchCard: typeof import('./components/user/MatchCard.vue')['default']
    Preloader: typeof import('./components/Preloader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInForm: typeof import('./components/SignInForm.vue')['default']
    SignUpForm: typeof import('./components/SignUpForm.vue')['default']
    UserEditProfile: typeof import('./components/user/UserEditProfile.vue')['default']
    UserFooter: typeof import('./components/user/UserFooter.vue')['default']
    UserHeader: typeof import('./components/user/UserHeader.vue')['default']
    UserMatchCard: typeof import('./components/user/UserMatchCard.vue')['default']
    UserProfile: typeof import('./components/user/UserProfile.vue')['default']
  }
}
