/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/account/Layout': RouteRecordInfo<'/account/Layout', '/account/Layout', Record<never, never>, Record<never, never>>,
    '/account/SignIn': RouteRecordInfo<'/account/SignIn', '/account/SignIn', Record<never, never>, Record<never, never>>,
    '/account/SignUp': RouteRecordInfo<'/account/SignUp', '/account/SignUp', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Layout': RouteRecordInfo<'/Layout', '/Layout', Record<never, never>, Record<never, never>>,
    '/user/Edit': RouteRecordInfo<'/user/Edit', '/user/Edit', Record<never, never>, Record<never, never>>,
    '/user/Layout': RouteRecordInfo<'/user/Layout', '/user/Layout', Record<never, never>, Record<never, never>>,
    '/user/Match': RouteRecordInfo<'/user/Match', '/user/Match', Record<never, never>, Record<never, never>>,
    '/user/Profile': RouteRecordInfo<'/user/Profile', '/user/Profile', Record<never, never>, Record<never, never>>,
  }
}
